# Generated by Django 4.2.1 on 2023-05-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(default=None, max_length=100)),
                ('counter', models.IntegerField(default=0)),
                ('otp_created_at', models.DateTimeField(default=None)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
