# Generated by Django 4.2.1 on 2023-05-19 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_blocked_at_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 49, 45, 153560, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 49, 45, 153560, tzinfo=datetime.timezone.utc)),
        ),
    ]
